DISCIPLINE_NAME = "NOM_DISCIPLINA"
DISCIPLINE_WORKLOAD = "VAL_CARGA_HORARIA"
DISCIPLINE_SYLLABUS = "DSC_EMENTA"
EQUIVALENT_DISCIPLINE_NAME = "EQ_NOM_DISCIPLINA"
EQUIVALENT_DISCIPLINE_WORKLOAD = "EQ_VAL_CARGA_HORARIA"
EQUIVALENT_DISCIPLINE_SYLLABUS = "EQ_DSC_EMENTA"
EQUIVALENCE_TYPE = "EQ_TIPO"

